<style type="text/css">
	.bg-white {
    
    -webkit-box-shadow: 0px 0px 5px 0px rgba(221, 221, 221, 1);
    -moz-box-shadow: 0px 0px 5px 0px rgba(221, 221, 221, 1);
    box-shadow: 0px 0px 5px 0px rgba(221, 221, 221, 1);
}
.pinside40 {
    padding: 40px;
}
.pinside30 {
    padding: 30px;
}
.mb30 {
    margin-bottom: 30px;
}
form {
    display: block;
    margin-top: 0em;
}
.form-title {
    border-bottom: 1px solid #e8e6df;
    padding-bottom: 19px;
    margin-bottom: 30px;
}
h2 {
    font-size: 22px;
}
input.form-control {
    background-color: #fdfdfb;
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    border-radius: 2px;
    border: 1px solid #e9e6e0;
    -webkit-box-shadow: inset 0 0px 0px rgba(0, 0, 0, .075);
    box-shadow: inset 0 0px 0px rgba(0, 0, 0, .075);
    font-family: 'Montserrat', sans-serif;
}


</style>
 <form >
		     <div class="bg-white pinside30">
                        <h2 class="form-title">ART</h2>
                                    <!-- Text input-->
                        <div class="form-group">
                                    <label class="label-title">Nombre</label>
                                    <input type="text" class="form-control">
                                </div>
                        <div class="form-group">
                                <label class="label-title">Cobertura</label>
                                <input type="text" class="form-control">
                            </div>
                        
                        <div class="form-group">
                                <label class="label-title">Telefono</label>
                                <div class="select">
                                    <select class="form-control">
                                        <option>Real Estate</option>
                                        <option>Restaurant</option>
                                        <option>Real Estate</option>
                                        <option>Health & Fitness</option>
                                        <option>Beauty & Spas</option>
                                        <option>Hotels & Travel</option>
                                        <option>Automotive</option>
                                    </select>
                                </div>
                            </div>
            </div>
            
	</form>