<div class="jumbotron">
    <table>
        <tr>
            <th>id </th>
            <th>Nombre </th>
            <th></th>
        </tr>
        <?php
            foreach ($usuarios as $usuario) {
                echo ('<tr>');
                echo ('<td>');
                echo ($usuario->getId());
                echo ('</td>');  
                echo ('<td>');
                echo ($usuario->getNombre());
                echo ('</td>'); 
                echo ('<td>');
            }        
        ?>
    </table>
</div>
