<?php  $permits ?>
<h1>Permisos realizados</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
	            <th>Id</th>
	            <th>Date</th>
	            <th>Empresa</th>
	            <th>Lugar de Trabajo</th>
	            <th>Etapa</th>
	            <th>Actividad</th>
        	</tr>
            <?php  foreach($permits['general'] as $row):?> 
            <tr>
                <td><?=$row->getId();?></td>
                <td><?=$row->getDate();?></td>
                <td><?=$row->getCompany();?></td>
                <td><?=$row->getWorkPlace();?></td>
                <td><?=$row->getWorkStage();?></td>
                <td><?=$row->getWorkActivity();?></td>
            </tr>
		    <?php endforeach;?>
        </table>
    </div>
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
	            <th>Id</th>
	            <th>Presion del equipo</th>
	            <th>Temperatura del equipo</th>
	            <th>Producto que maneja</th>
        	</tr>
            <?php  foreach($permits['residual'] as $row):?> 
            <tr>
                <td><?=$row->getId();?></td>
                <td><?=$row->getTeamPressure();?></td>
                <td><?=$row->getTeamTemperature();?></td>
                <td><?=$row->getProducts();?></td>
            </tr>
		    <?php endforeach;?>
        </table>
    </div>
</div>
