<?php
$this->headTitle('Permisos');
$this->mainMenu()->setActiveItemId('Modulos');


?>
<script type="text/javascript" src ="js/operation/permits/cold.js"></script>

      
   <div class="container">
    <div class="row">
    <section>
        <div class="wizard">
            <div class="wizard-inner">
                <div class="connecting-line"></div>
                <ul class="nav nav-tabs" role="tablist">
                  <?php foreach ($tabs as $key=> $tab): ?>
                    <li role="presentation" 
                        class=<?=($key == 0) ?  "active" :  "disabled"?>>
                        <a href="#<?=$tab->getName()?>" data-toggle="tab" aria-controls="step<?=  $i?>" role="tab" title="Step<?=  $i?>">
                            <span class="round-tab">
                                <i class="glyphicon <?=$tab->getIcon()?>"></i>
                            </span>
                        </a>
                    </li>
                  <?php endforeach;?> 
                    
                </ul>
            </div>
            
            <form role="form">
                <div class="tab-content ">  
                  <?php
                      $i = 1; 
                      foreach ($forms as $key => $form): 
                  ?>
                  
                  <div class="tab-pane <?=($i == 1) ?  "active" :  " "?>" role="tabpanel" id="<?=$key?>">
                    <?= $form?> 
                    <ul class="list-inline pull-right">
                        <li><button type="button" class="btn btn-default prev-step">Previous</button></li>
                        <li><button type="button" class="btn btn-primary next-step">Save and continue</button></li>   
                    </ul>
                  </div>
                  
                  <?php $i++;  
                        endforeach; 
                  ?>      
                </div>
      
            </form>
        </div>
    </section>
   </div>
</div>