<div class="jumbotron">
    <table>
        <tr>
            <th>id</th>
            <th>Nombre</th>
        </tr>
        <?php
        echo ($hola);
            /*foreach ($operations as $operation) {
                echo ('<tr>');
                echo ('<td>');
                echo ($operation->getId());
                echo ('</td>');  
                echo ('<td>');
                echo ($operation->getNombre());
                echo ('</td>');                
                echo ('</tr>');
            }       */
        ?>
    </table>
</div>
