<?php
$this->headTitle('Ver Permiso');



?>

<h1 align="center">Validar Permiso</h1>
<br>
<div class="row">
    <div class="col-xs-12">
        <caption><h4>Datos Generales</h4></caption>
        <table class="table table-striped table-bordered">
             <tr>
                <th style="width: 30%">Número de Permiso:</th>
                <td><?= $this->escapeHtml($workPermit->getId()) ?></td>
            </tr>
            <tr>
                <th>Hora de Inicio:</th>
                <td><?= $this->escapeHtml($workPermit->getStartTime()) ?></td>
            </tr>
            <tr>
                <th>Hora de Finalizacion:</th>
                <td><?= $this->escapeHtml($workPermit->getEndTime()) ?></td>
            </tr>
            <tr>
                <th>Motivo de trabajo:</th>
                <td><?= $this->escapeHtml($workPermit->getWorkReason()) ?></td>
            </tr>
            <tr>
                <th>Fecha de Creacion:</th>
                <td><?= $this->escapeHtml($workPermit->getDateCreated()->format('d/m/Y')) ?></td>
            </tr>
            <tr>
                <th>Contratista:</th>
                <td><?= $this->escapeHtml($workPermit->getContractor()->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Ejecutor del Permiso:</th>
                <td><?= $this->escapeHtml($workPermit->getPerformer()->getFullName()) ?></th>
            </tr>
        </table>
    </div>
</div>
<?php foreach ($sections as $name => $items): ?>
<div class="row">
    <div class="col-xs-12">
        <caption><h4><?=$name?></h4></caption>
        <table class="table table-striped table-bordered">
            <?php foreach ($items as $key => $item): ?>
                <tr>
                    <?php if ($item->getSelect() == 'A'): ?>
                    <th style="width: 30%"><?=$item->getType()->getName()?></th>
                    <td><?=$item->getName()?></td>
                    <?php endif ?>
                </tr>            
                                    
            <?php endforeach ?>
             
            
        </table>
    </div>
</div>
<?php endforeach ?>
<div class="row">
    <div class="col-xs-12">
        <caption><h4>Empresa del Contratista "<?=$workPermit->getContractor()->getCompany()[0]->getName()?>"</h4></caption>
        <table class="table table-striped table-bordered">
                <?php foreach ($personals as  $personal): ?>
                    <tr>
                        <th style="width: 30%">Empleado</th>
                        <td><?=$personal->getFullName()?></td>
                    </tr>            
                <?php endforeach ?>
        </table>
    </div>
</div>
<form id="formModule" method="POST" action="<?= $this->url('workPermit', 
                        ['action'=>'complete', 'id'=>$workPermit->getId()]); ?>" > 
                <input type="hidden" id="validar" name="validar" value="">

<script type="text/javascript">
    function canceled()
    {
        $('input:hidden').val("canceled");
        $('#formModule').submit();  
    }
    function acepted()
    {
        $('input:hidden').val("acepted");
        $('#formModule').submit();  
    }

    $(document).ready(function(){
        document.getElementById("btn-left").style.display = "none";
        document.getElementById("btn-right").setAttribute("class","btn btn-primary submit  glyphicon glyphicon-remove btn-lg");
        document.getElementById("btn-right").onclick=function(){canceled()};
        document.getElementById("btn-submit").onclick=function(){acepted()};

 });
</script>