<?php
$this->headTitle('Permiso');


?>

<h1 align="center">Permisos</h1>
<br>


<table class="table table-striped ">

   <tr>
        <th>ID</th>
        <th>Fecha de Creación</th>
        <th>Hora de Inicio</th>
        <th>Hora de Finalizacion</th>
        <th>Motivo de trabajo</th>
        <?php if ($isContractor): ?>
            <th>Responsable</th>
        <?php else: ?>
            <th>Contratista</th>
        <?php endif ?>
    </tr>
    
    <?php foreach ($workPermit as $permit): ?>
    
    <tr>
        <td><?= $this->escapeHtml($permit->getId()); ?></td>
        <td>
            <a href="<?= $this->url('workPermit', ['action'=>'view', 'id'=>$permit->getId()]); ?>">
                <?= $this->escapeHtml($permit->getDateCreated()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($permit->getStartTime()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($permit->getEndTime()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($permit->getWorkReason()); ?></a> 
        </td>
        <?php if ($isContractor): ?>
            <td><?= $this->escapeHtml($permit->getPerformer()->getFullName()); ?></td>    
        <?php else: ?>
            <td><?= $this->escapeHtml($permit->getContractor()->getFullName()); ?></td>        
        <?php endif ?>
        
        <td>
            <a class="btn btn-info" href="<?= $this->url('workPermit', 
                    ['action'=>'edit', 'id'=>$permit->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<script type="text/javascript">
    $(document).ready(function(){
        document.getElementById("btn-left").style.display = "none";
        document.getElementById("btn-right").style.display = "none";
        document.getElementById("btn-submit").style.display = "block";

        document.getElementById("btn-submit").classList.remove('glyphicon-ok');
        document.getElementById("btn-submit").classList.add('glyphicon-plus');
        
        var att = document.createAttribute("onClick");        
        att.value = 'location.href= "workPermit/add"';
        
        document.getElementById("btn-submit").setAttributeNode(att);


 });
</script>