<?php
$this->headTitle('Change Password');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            'Change Password'=>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
            ]);

$form->get('old_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter old password'
    ]);

$form->get('new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter new password'
    ]);

$form->get('confirm_new_password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Re-enter new password'
    ]);



$form->prepare();
?>

<h1 align="center">Cambiar Password</h1>
<br>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('old_password')); ?>
            <?= $this->formElement($form->get('old_password')); ?>
            <?= $this->formElementErrors($form->get('old_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
      
       
    </div>    
</div>   


<script type="text/javascript">
    $(document).ready(function(){
        document.getElementById("btn-left").style.display = "none";
        document.getElementById("btn-right").style.display = "none";

 });
</script>