<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>

<h1 align="center">Usuarios</h1>

<br>
<table class="table table-striped ">

   <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th>Full Name</th>
        <th>Date Created</th>
        <th>Status</th>
        <th>Perfil</th>
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($users as $user): ?>
    
    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>
        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getEmail()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($user->getFullName()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>        
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td><?= $this->escapeHtml($user->getProfile(0)->getName()); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('users', 
                    ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-default" href="<?= $this->url('users',
                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> Change Password
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<script type="text/javascript">
    $(document).ready(function(){
        document.getElementById("btn-left").style.display = "none";
        document.getElementById("btn-right").style.display = "none";
        document.getElementById("btn-submit").style.display = "block";

        document.getElementById("btn-submit").classList.remove('glyphicon-ok');
        document.getElementById("btn-submit").classList.add('glyphicon-plus');
        
        var att = document.createAttribute("onClick");        
        att.value = 'location.href= "users/add"';
        
        document.getElementById("btn-submit").setAttributeNode(att);


 });
</script>