<?php
$this->headTitle('Permiso');


?>

<h1 align="center">Permisos</h1>
<br>


<table class="table table-striped ">

   <tr>
        <th>Nº </th>
        <th>Fecha de Creación</th>
        <th>Hora de Inicio</th>
        <th>Hora de Finalizacion</th>
        <th>Motivo de trabajo</th>
        <th>Responsable</th>
    </tr>
    
    <?php foreach ($workPermit as $permit): ?>
    
    <tr>
        <td><?= $this->escapeHtml($permit->getId()); ?></td>
        <td>
            <a href="<?= $this->url('workPermitContractor', ['action'=>'view', 'id'=>$permit->getId()]); ?>">
                <?= $this->escapeHtml($permit->getDateCreated()->format('d/m/Y')); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($permit->getStartTime()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($permit->getEndTime()); ?></a> 
        </td>
        <td><?= $this->escapeHtml($permit->getWorkReason()); ?></a> 
        </td>
            <td><?= $this->escapeHtml($permit->getPerformer()->getFullName()); ?></td>
        <td>
            <?php if ($permit->getStatus() == $statusActived): ?>
                <a class="btn btn-info" href="<?= $this->url('workPermitContractor', 
                    ['action'=>'complete', 'id'=>$permit->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> </a>
            <?php else: ?>  
                    <a class="btn btn-info" href="<?= $this->url('workPermit', 
                        ['action'=>'view', 'id'=>$permit->getId()]); ?>">
                    <span class="glyphicon glyphicon-eye-open" ></span> </a>
            <?php endif ?>
            
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<script type="text/javascript">
    $(document).ready(function(){
        document.getElementById("btn-left").style.display = "none";
        document.getElementById("btn-right").style.display = "none";
        document.getElementById("btn-submit").style.display = "none";



 });
</script>