<?php
$this->headTitle('Ver Permiso');



?>

<h1 align="center">Ver Permiso</h1>
<br>
<div class="row">
    <div class="col-xs-12">
        <caption><h4>Datos Generales</h4></caption>
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($workPermit->getId()) ?></th>
            </tr>
            <tr>
                <th>Hora de Inicio:</th>
                <td><?= $this->escapeHtml($workPermit->getStartTime()) ?></th>
            </tr>
            <tr>
                <th>Hora de Finalizacion:</th>
                <td><?= $this->escapeHtml($workPermit->getEndTime()) ?></th>
            </tr>
            <tr>
                <th>Motivo de trabajo:</th>
                <td><?= $this->escapeHtml($workPermit->getWorkReason()) ?></th>
            </tr>
            <tr>
                <th>Fecha de Creacion:</th>
                <td><?= $this->escapeHtml($workPermit->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Contratista:</th>
                <td><?= $this->escapeHtml($workPermit->getContractor()->getFullName()) ?></th>
            </tr>
        </table>
    </div>
</div>
<?php foreach ($sections as $name => $items): ?>
<div class="row">
    <div class="col-xs-12">
        <caption><h4><?=$name?></h4></caption>
        <table class="table table-striped table-bordered">
            <?php foreach ($items as $key => $item): ?>
                <tr>
                    <?php if ($item->getSelect() == 'A'): ?>
                    <th><?=$item->getType()->getName()?></th>
                    <td><?=$item->getName()?></td>
                    <?php endif ?>
                </tr>            
                                    
            <?php endforeach ?>
             
            
        </table>
    </div>
</div>
<?php endforeach ?>

<div class="row">
    <div class="col-xs-12">
        <caption><h4>Empresa del Contratista "<?=$workPermit->getContractor()->getCompany()[0]->getName()?>"</h4></caption>
        <table class="table table-striped table-bordered">
                <?php foreach ($personals as  $personal): ?>
                    <tr>
                        <th style="width: 30%">Empleado</th>
                        <td><?=$personal->getFullName()?></td>
                    </tr>            
                <?php endforeach ?>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        document.getElementById("btn-left").style.display = "none";
        document.getElementById("btn-right").style.display = "none";
        document.getElementById("btn-submit").style.display = "none";

 });
</script>