<?php
$this->headTitle('Ver Permiso');



?>

<h1 align="center">Ver Permiso</h1>
<br>
<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($workPermit->getId()) ?></th>
            </tr>
            <tr>
                <th>Hora de Inicio:</th>
                <td><?= $this->escapeHtml($workPermit->getStartTime()) ?></th>
            </tr>
            <tr>
                <th>Hora de Finalizacion:</th>
                <td><?= $this->escapeHtml($workPermit->getEndTime()) ?></th>
            </tr>
            <tr>
                <th>Motivo de trabajo:</th>
                <td><?= $this->escapeHtml($workPermit->getWorkReason()) ?></th>
            </tr>
            <tr>
                <th>Fecha de Creacion:</th>
                <td><?= $this->escapeHtml($workPermit->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        document.getElementById("btn-left").style.display = "none";
        document.getElementById("btn-right").style.display = "none";
        document.getElementById("btn-submit").style.display = "none";

 });
</script>