<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Cedna')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/login/login.css'))
                        ->prependStylesheet($this->basePath('css/modules/modules.css'))
                        ->prependStylesheet($this->basePath('css/operation/permits/cold.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/flexboxgrid.min.css'))
                        ->prependStylesheet($this->basePath('css/operation/permits/forms/multi-select.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>

    </head>
    <body>
        <div class="container">
            <div class="row  ">
                <!-- Page header -->
                <div class="col-xs-12">
                    <div class="app-caption">Sistema de Permiso de Trabajo</div>
                </div>                
            </div>
       
            <div class="row container">
                <div id="content" class="col-xs-12 content">
                    <!-- Page content placeholder -->
                    <?= $this->content; ?>
                </div>
            </div>
       
            
            <footer>
                <!-- <p>&copy; 2005 - <?= date('Y') ?>  Argosoft </p> -->
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
