
        <fieldset>

          <!-- Form Name -->
          <legend>Riesgos Ambientales</legend>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Disponibles</label>
            <div class="col-sm-10">
              	<select id='pre-selected-options' name="environmental[elements]" multiple='multiple'>
				    <option value='elem_1' selected>Existe posibilidad de algun tipo de derrame o emision</option>
				    <option value='elem_2' selected>Se colocaron los equipos, elementos o barreras necesarias</option>
				</select>
            </div>
          </div>

   



        </fieldset>

<script src="js/operation/permits/forms/jquery.multi-select.js"></script>
<script type="text/javascript">
  // run pre selected options
  $('#pre-selected-options').multiSelect();
  </script>