
  
        
          <!-- Form Name -->
          <legend>General</legend>
          
          <!-- Text input-->
          <div class="form-group row center-xs " > 
              <div class="col-xs-4 col-md-4  ">
                  <img src="http://www.personalbrandingblog.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640-300x300.png" class="img-thumbnail" alt="Cinque Terre">
              </div>
          </div>   
          
          <div class="form-group">
              <div class="col-sm-8">
                  <label class="radio-inline"><input type="radio" name="general[optradio]" checked>Externo</label>
                  <label class="radio-inline"><input type="radio" name="general[optradio]">Interno</label>
              </div>
          </div>

          <!-- Text input-->
          <div class="form-group">
              <label class="col-sm-2 control-label" for="textinput">Empresa</label>
              <div class="col-sm-8">
                  <select name="general[company]" class="form-control" id="sel1">
                      <option value="coca-cola" selected>Coca-cola</option>
                      <option value="claro">Claro</option>
                      <option value="nextel">Nextel</option>
                      <option value="microsoft">Microsoft</option>
                  </select>
              </div>
          </div>
        
          <!-- Text input-->
          <div class="form-group">
              <label class="col-sm-2 control-label" for="textinput">Planta</label>
              <div class="col-sm-8">
                  <select name="general[workplace]" class="form-control" id="sel1">
                      <option value="tecnica" selected>Tecnica</option>
                      <option value="soldadura">Soldadura</option>
                  </select>   
              </div>
          </div>
          
           <!-- Text input-->
          <div class="form-group ">
              <label class="col-sm-2 control-label" for="textinput">Etapa</label>
              <div class="col-sm-3">
                  <select name="general[workstage]" class="form-control" id="sel1">
                      <option>Pintura</option>
                      <option>Yeso</option>
                      <option>Mampo</option>
                  </select>
              </div>
              <label class="col-sm-2 control-label" for="textinput">Actividad</label>
              <div class="col-sm-3">
                  <select name="general[workactivity]" class="form-control" id="sel1">
                      <option>Romper</option>
                      <option>Lavar</option>
                  </select>
              </div>
          </div>
        </input>

