
        <fieldset>
        
          <!-- Form Name -->
          <legend>General</legend>
          
          <!-- Text input-->
          <div class="form-group" >
            <label class="col-sm-3 control-label" for="textinput">Fecha</label>
            <div class="col-sm-4">
              <input type="date" name="general[date]" placeholder="Address Line 1" class="form-control">
            </div>  
            <div class="col-sm-6 col-xs-12 ">
              <img src="http://neoleader.com.br/wp-content/uploads/2015/05/geral_adulto-300x300.png" class="img-thumbnail" alt="Cinque Terre">
            </div>
          </div>   
          <div class="form-group">
            <div class="col-sm-10">
              <label class="radio-inline"><input type="radio" name="general[optradio]" checked>Externo</label>
              <label class="radio-inline"><input type="radio" name="general[optradio]">Interno</label>
            </div>
          </div>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Empresa</label>
            <div class="col-sm-10">
              <select name="general[company]" class="form-control" id="sel1">
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
              </select>
            </div>
          </div>
        
          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Planta</label>
            <div class="col-sm-10">
              <select name="general[workplace]" class="form-control" id="sel1">
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
              </select>   
            </div>
          </div>
          
           <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Etapa</label>
            <div class="col-sm-4">
              <select name="general[workstage]" class="form-control" id="sel1">
                <option>Pintura</option>
                <option>Yeso</option>
                <option>Mampo</option>
              </select>
            </div>
            <label class="col-sm-2 control-label" for="textinput">Actividad</label>
            <div class="col-sm-4">
              <select name="general[workactivity]" class="form-control" id="sel1">
                <option>Pintura</option>
                <option>Yeso</option>
                <option>Mampo</option>
              </select>
            </div>
          </div>
        </input>
        

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="pull-right">
               <!--  <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button> -->
                <input type="submit" value="Submit">
              </div>
            </div>
          </div>

          
        </fieldset>
