
	<form>
		<h1>Proteccion</h1>
		  <select id='pre-selected-options' multiple='multiple'>
		    <option value='elem_1' selected>elem 1</option>
		    <option value='elem_2'>elem 2</option>
		    <option value='elem_3'>elem 3</option>
		    <option value='elem_4' selected>elem 4</option>
		</select>
	</form>


<script src="js/operation/permits/forms/jquery.multi-select.js"></script>
<script type="text/javascript">
  // run pre selected options
  $('#pre-selected-options').multiSelect();
  </script>