
    <fieldset>
          <!-- Form Name -->
          <legend>Proteccion</legend>

          <!-- Text input-->
          <div class="form-group row center-xs">
	            <div class=" col-md-12">
	              	<select id='pre-selected-options' name="protection[elements][]" multiple='multiple'>
					    <option value='elem_1' selected>Respirador de vapores</option>
					    <option value='elem_2' selected>Respirador de vapores</option>
					    <option value='elem_3'>Respirador para polvos</option>
					    <option value='elem_4'>Visera o careta</option>
					    <option value='elem_5'>Botas</option>
					    <option value='elem_6'>Equipo de rescaste</option>
					</select>
	            </div>
          </div>
     </fieldset>


<script src="js/operation/permits/forms/jquery.multi-select.js"></script>
<script type="text/javascript">
  // run pre selected options
  $('#pre-selected-options').multiSelect();
  </script>