<?php
$this->headTitle('View Personal');



?>

<h1 align="center">Ver Personal</h1>
<br>
<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($personal->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($personal->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Nombre:</th>
                <td><?= $this->escapeHtml($personal->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Antigüedad:</th>
                <td><?= $this->escapeHtml($personal->getSeniority()) ?></th>
            </tr>
            <tr>
                <th>Fecha de Creacion:</th>
                <td><?= $this->escapeHtml($personal->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        document.getElementById("btn-left").style.display = "none";
        document.getElementById("btn-right").style.display = "none";
        document.getElementById("btn-submit").style.display = "none";

 });
</script>