<?php
use DBAL\Entity\Module;
$this->headTitle('About');
$rutaAction = $this->url('about'); 
$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'About'=>$this->url('about'),
            ]);
?>
<script type="text/javascript" src ="js/jquery-2.2.4.min.js"></script>

<script >
	function llamarFuncion(moduleId)
	{
		$('input:hidden').val(moduleId);
		$('#formModule').submit();
	}
</script>

<h1 align="center">Modulos de <?= $this->escapeHtml($profileName) ?></h1>


<div class="flex-container">
<form id="formModule" method="POST" action="<?=$rutaAction?>" >
	<?php foreach ($profileModules as $modules): ?>
		<button onclick="llamarFuncion(<?php echo ($modules->getId()); ?>)" class="button glyphicon glyphicon-user"> <?= $this->escapeHtml($modules->getName()) ?>
		</button>
		<input type="hidden" id="custId" name="custId" value="">
	<?php endforeach; ?> 
</form>
</div>	
