<?php
use DBAL\Entity\Module;
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'About'=>$this->url('about'),
            ]);
?>

<h1 align="center">Modulos de <?= $this->escapeHtml($profileName) ?></h1>


<div class="flex-container">

	<?php foreach ($profileModules as $modules): ?>
		<button href="#" class="button glyphicon glyphicon-user"> <?= $this->escapeHtml($modules->getName()) ?>
		</button>
	<?php endforeach; ?> 
</div>	
